name: Release v3
on:
  push:
    branches:
      - develop
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@develop
      - name: Use Node.js 12.14
        uses: actions/setup-node@v1
        with:
          node-version: '12.14'
      - name: Build Files
        run: |
          npm install
          npm run build:deploy-files
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: build
          REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR_DEVELOP }}
          ARGS: --verbose --exclude=ystandard-info.json